config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :properties, only: [:index, :show] do
    resources :bids, only: [:show]
  end

  resources :users do
    resources :properties do
      resources :bids, only: [:create]
    end
  end

  root 'properties#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
  validates :username, :first_name, :last_name, :address, presence: true

  has_many :notifications
  has_many :bids
  has_many :properties

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  private

  def sign_up_params
    params.require(:user).permit(:username, :address, :first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :address, :first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show; end

  def edit; end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    accessible = [ :name, :email, :last_name, :username ] # extend with your own params
    accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/finish_sign_up.html.haml
#add-email.container
  %h1 Add Email
  = form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f|
    - if @show_errors && current_user.errors.any?
      #error_explanation
        - current_user.errors.full_messages.each do |msg|
          = msg
          %br/
    .form-group
      = f.label :email
      .controls
        = f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com'
        %p.help-block Please confirm your email address. No spam.
    .actions
      = f.submit 'Continue', :class => 'btn btn-primary'

app/views/users/show.html.haml
.row
  .col
    %h4 Personal info
    %hr
    %ul
      %li #{ @user.name } #{ @user.last_name }
      %li #{ @user.username }
      %li #{ @user.email }
      %li #{ @user.address }
.row
  .col
    %h4 Properties
    %hr
    - @user.properties.in_groups_of(3).each do |property_group|
      .row
        - property_group.each do |property|
          - if property  
            .col
              .row.justify-content-center.band-summary
                - if property.photos.any?
                  = link_to "#{image_tag(property.photos.first.url)}".html_safe, property
                - else
                  = link_to "#{image_tag('property-placeholder.png')}".html_safe, property
- if current_user == @user  
  .row
    .col
      %h4 Bids
      %hr
      - @user.bids.in_groups_of(3).each do |bid_group|
        .row
          - bid_group.each do |bid|
            - if bid  
              .col
                .row.justify-content-center.band-summary
                  = link_to "Property ID: #{bid.property.identifier}, for #{bid.price_bided}".html_safe, property_path(bid.property)