config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :properties, only: [:index, :show] do
    resources :bids, only: [:show]
  end

  resources :users do
    resources :properties do
      resources :bids, only: [:create]
    end
  end

  root 'properties#index'
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
  has_one :property_type
  has_many :photos
  has_many :features
  has_many :bids
end

app/models/property_type.rb
class PropertyType < ActiveRecord::Base
  validates :name, presence: true

  has_many :properties
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  before_action :find_property, only: [:show]

  def index
    @properties = Property.all
  end

  def show
    @bid = Bid.new
  end

  private

  def find_property
    @property = Property.find(params[:id])
  end

end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/index.html.haml
- @properties.in_groups_of(3).each do |property_group|
  .row
    - property_group.each do |property|
      - if property  
        .col
          .row.justify-content-center.band-summary
            - if property.photos.any?
              = link_to "#{image_tag(property.photos.first.url)}".html_safe, property
            - else
              = link_to "#{image_tag('property-placeholder.png')}".html_safe, property
          .row.justify-content-center
            %p Posted by #{ property.user.username }

app/views/properties/show.html.haml
.row
  .col
    %hr
    %h4 Property information
    %hr
    %ul
      %li
        Address: #{ @property.address }
      %li
        Price: #{ number_to_currency(@property.price, locale: :en) }
    %hr
    %h4 Features
    %hr
    %ul
      - @property.features.each do |feature|
        %li
          #{ feature.description } hahaha
  .col
    %hr
    %h4 Owner contact info
    %hr
    %ul.pb-1
      %li
        #{ @property.user.name } #{ @property.user.last_name }
      %li
        #{ @property.user.username }
      %li
        #{ @property.user.email }
    - if user_signed_in?
      %hr
      %h4 Bid for this property
      %hr
      - if current_user != @property.user
        = form_for([current_user, @property, @property.bids.build]) do |f|
          = f.number_field :price_bided
          = f.number_field :user_id, hidden: true, value: current_user.id
          = f.number_field :property_id, hidden: true, value: @property.id
          = f.submit
    - else
      %hr
      %h4 Sign in or sign up in order to bid
      %hr

- if @property.bids.count > 0
  %hr
  %h4 Bids
  %hr
  - @property.bids.in_groups_of(5).each do |bid_group|
    .row
      - bid_group.each do |bid|
        - if bid && bid.user
          .col
            #{ link_to "#{bid.user.try(:username)}", user_path(bid.user) } bided for #{ number_to_currency(bid.price_bided, locale: :en) }

.row 
  .col
    %hr
    %h4 Photos
    %hr
    - @property.photos.in_groups_of(3).each do |photo_group|
      .row.pb-5
        - photo_group.each do |photo|
          - if photo
            .col.band-summary
              = image_tag photo.url